### PR TITLE
update to the unit tests and linking column user friendly names problem

### PR DESCRIPTION
**Pull request by ami-day**
- Updated unit tests

- Solved linking column user friendly names problem

### CODE REVIEW

**Comment by aaclan-ebi** [comment]
Seems like these are integration/functional tests rather than unit tests.

**Comment by ami-day** [comment]
> Seems like these are integration/functional tests rather than unit tests.

I may have an incorrect understanding/interpretation of extent at which a test is a unit test, or an integration/functional test, but either way, for now I need these tests whatever they are to check what I want to work is working. It would be really great if we could have some kind of meeting/presentation/talk about the philosophy of testing in the context of our goals and our team e.g. what is too little, what is too much, what kinds of tests to do and what their definitions are and in the context of this template spreadsheet generator work as a case study. Volunteers anyone?!

**Comment by aaclan-ebi** [comment]
@ami-day I'm happy to give one :) I'll talk with Karoy!

Having these integration/functional tests here is totally fine 👍 . Just want to note it since the PR title is a bit misleading.

**Comment by ami-day** [comment]
> @ami-day I'm happy to give one :) I'll talk with Karoy!
> 
> Having these integration/functional tests here is totally fine 👍 . Just want to note it since the PR title is a bit misleading.

Yea i understand. Once I've got a better idea of testing, hopefully my PR titles will make more sense to people. Having a talk would be really appreciated!

**Review by rdgoite — APPROVED** [review]

**Pull request merged**
