### PR TITLE
Update python dependencies, removed pinning

### PR DESCRIPTION
**Pull request by aaclan-ebi**
Fixing this as I encounter some errors while i'm setting up my new laptop

### CODE REVIEW

**Review by rolando-ebi — COMMENTED** [review]
@aaclan-ebi can you confirm that this successfully builds in quay.io? Or even in your own local docker daemon

**Comment by aaclan-ebi** [comment]
yup, docker image is being built.

**Comment by aaclan-ebi** [comment]
ingest integration test passed beyond importing in dev, will merge this now

https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/252925

Was able to manually generate a template spreadsheet as well.

**Comment by aaclan-ebi** [comment]
Integration test is passing in dev with this image deployed.

**Pull request merged**
