### PR TITLE
Dcp 417 download links

### PR DESCRIPTION
**Pull request by aaclan-ebi**
ebi-ait/dcp-ingest-central#417

### CODE REVIEW

**Review by ke4 — CHANGES_REQUESTED** [review]
It looks like a breaking change to me.
Could we add a unit test, please?

**Comment by aaclan-ebi** [comment]
@ke4 how do you think should this be tested?

**Comment by ke4** [comment]
> @ke4 how do you think should this be tested?

@aaclan-ebi You should test this line:
`flattened_json = self.downloader.convert_json(entity_list)`
as its input parameter type has change to a `list` and this look to me a braking change.
Thanks

**Comment by aaclan-ebi** [comment]
Hi @ke4 , 

```
 entity_dict = self.data_collector.collect_data_by_submission_uuid(submission_uuid)
 entity_list = list(entity_dict.values())
flattened_json = self.downloader.convert_json(entity_list)
```
> as its input parameter type has changed to a list 

It didn't change. The output of `collect_data_by_submission_uuid` is the one that changed. It used to return a list now, it's returning a dictionary. The `collect_data_by_submission_uuid` function already has unit tests.

There is no complicated logic in the `export` function and unit tests wouldn't really give a lot of value. It's just calling methods that already have unit tests. 

This is the unit test that I came up with for the `export` function, do you think I should add this? It involves a lot of mocking because it's really just calling methods from its dependencies.
```
    @patch('ingest.downloader.downloader.XlsDownloader.convert_json')
    @patch('ingest.downloader.data_collector.DataCollector.collect_data_by_submission_uuid')
    @patch('ingest.downloader.downloader.XlsDownloader.create_workbook')
    def test_export(self, create_workbook, collect_data_by_submission_uuid, convert_json):
        # given 

        ingest_api = Mock()
        create_workbook.return_value = 'mock_workbook'
        collect_data_by_submission_uuid.return_value = {'key': 'value'}
        export_service = ExportToSpreadsheetService(ingest_api)
        submission_uuid = 'submission-uuid'

        # when 
        workbook = export_service.export(submission_uuid)

        # then
        self.assertEqual(workbook, 'mock_workbook')
        ingest_api.unset_token.assert_called()
        collect_data_by_submission_uuid.assert_called_with(submission_uuid)
        convert_json.assert_called_with(['value'])
```

If you can give me a test case (given when then) which you want to test for the export function behaviour, please let me know.

The integration test which we already have for the bulk update should already cover the integration of how these methods all work together in the `ExportToSpreadsheetService.export` function.

**Comment by ke4** [comment]
@aaclan-ebi We discussed this offline and it seems that there is no real change here as the `collect_data_by_submission_uuid` method was retuning a `list` in the previous version.
I am going to approve your change. No need to add more unit tests. Sorry about my misunderstanding of the code.

**Review by ke4 — DISMISSED** [review]
LGTM 👍

**Comment by aaclan-ebi** [comment]
Thanks @ke4 ! No need to say sorry! I appreciate that you always wanna make sure we have tests! Thanks!!!

**Review by jacobwindsor — APPROVED** [review]

**Review by ke4 — APPROVED** [review]

**Pull request merged**
